// Shape of verified research records generated by scripts/import-research.ts.

export type ResearchPlan = {
  plan: string;
  price: number | null;
  currency: string | null;
  billingPeriod: "MONTHLY" | "ANNUAL" | "FREE" | "CUSTOM" | string;
  unit: string | null;
  perSeat: boolean;
  promotional: boolean;
  notes: string | null;
  evidence: string;
};

export type ResearchRecord = {
  checkedAt: string;
  sources: { kind: string; url: string; name: string }[];
  facts: { key: string; value: string; sourceUrl: string; evidence: string }[];
  pricing: {
    status: "verified" | "js_rendered" | "custom_only" | "unavailable";
    sourceUrl: string | null;
    currencySeen: string | null;
    regionDependent: boolean;
    regionNote: string | null;
    plans: ResearchPlan[];
  };
};
